import importlib.util
import importlib.machinery
import json
import os
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
CLI = ROOT / "bin" / "second-opinion"


def load_cli_module():
    loader = importlib.machinery.SourceFileLoader("second_opinion_cli", str(CLI))
    spec = importlib.util.spec_from_loader("second_opinion_cli", loader)
    module = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


class RegistryTests(unittest.TestCase):
    def test_required_agents_are_registered(self):
        module = load_cli_module()
        self.assertEqual({"codex", "claude", "opencode", "grok"}, set(module.AGENTS))

    def test_each_skill_mentions_every_target(self):
        module = load_cli_module()
        for agent in module.AGENTS.values():
            skill = module.render_skill(agent)
            self.assertIn(module.MARKER, skill)
            self.assertIn("second-opinion ask auto", skill)
            for key in module.AGENTS:
                self.assertIn(f"`{key}`", skill)

    def test_managed_write_skips_unmanaged_existing_files(self):
        module = load_cli_module()
        with tempfile.TemporaryDirectory() as temp:
            path = Path(temp) / "SKILL.md"
            path.write_text("user content", encoding="utf-8")
            status = module.managed_write(path, "generated", force=False, dry_run=False)
            self.assertEqual("skipped-existing", status)
            self.assertEqual("user content", path.read_text(encoding="utf-8"))


class CliCommandTests(unittest.TestCase):
    def run_cli(self, *args, home=None):
        env = os.environ.copy()
        if home:
            env["SECOND_OPINION_HOME"] = str(home)
        return subprocess.run(
            [str(CLI), *args],
            cwd=str(ROOT),
            env=env,
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            check=False,
        )

    def test_install_all_writes_expected_skill_files(self):
        with tempfile.TemporaryDirectory() as temp:
            home = Path(temp)
            result = self.run_cli("install", "--all", "--yes", home=home)
            self.assertEqual(result.returncode, 0, result.stderr)
            expected = [
                home / ".agents/skills/second-opinion/SKILL.md",
                home / ".claude/skills/second-opinion/SKILL.md",
                home / ".config/opencode/skills/second-opinion/SKILL.md",
                home / ".grok/skills/second-opinion/SKILL.md",
            ]
            for path in expected:
                self.assertTrue(path.exists(), path)
                self.assertIn("Generated by Second Opinion", path.read_text(encoding="utf-8"))

    def test_status_json_is_valid(self):
        with tempfile.TemporaryDirectory() as temp:
            result = self.run_cli("status", "--json", home=Path(temp))
            self.assertEqual(result.returncode, 0, result.stderr)
            payload = json.loads(result.stdout)
            self.assertEqual(payload["version"], "1.0.3")
            self.assertIn("codex", payload["agents"])

    def test_ask_dry_run_builds_grok_prompt_after_single_flag(self):
        result = self.run_cli("ask", "grok", "--dry-run", "--", "review this")
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertIn("grok", result.stdout)
        self.assertIn("-p", result.stdout)
        self.assertIn("review this", result.stdout)

    def test_codex_dry_run_uses_current_exec_flags(self):
        result = self.run_cli("ask", "codex", "--dry-run", "--", "review this")
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertIn("codex exec", result.stdout)
        self.assertIn("--sandbox read-only", result.stdout)
        self.assertNotIn("--ask-for-approval", result.stdout)

    def test_claude_dry_run_uses_normal_auth_mode(self):
        result = self.run_cli("ask", "claude", "--dry-run", "--", "review this")
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertIn("claude -p --permission-mode plan", result.stdout)
        self.assertNotIn("--bare", result.stdout)

    def test_timeout_flag_is_deprecated_noop(self):
        module = load_cli_module()
        source = CLI.read_text(encoding="utf-8")
        self.assertIn("Deprecated and ignored", source)
        self.assertNotIn("TimeoutExpired", source)
        self.assertNotIn("timeout=", source)
        self.assertEqual(module.VERSION, "1.0.3")


if __name__ == "__main__":
    unittest.main()
