import importlib.util
import importlib.machinery
import json
import os
import subprocess
import sys
import tempfile
import time
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
CLI = ROOT / "bin" / "second-opinion"


def load_cli_module():
    loader = importlib.machinery.SourceFileLoader("second_opinion_cli", str(CLI))
    spec = importlib.util.spec_from_loader("second_opinion_cli", loader)
    module = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


class RegistryTests(unittest.TestCase):
    def test_required_agents_are_registered(self):
        module = load_cli_module()
        self.assertEqual({"codex", "claude", "opencode", "grok", "antigravity"}, set(module.AGENTS))

    def test_each_skill_mentions_every_target(self):
        module = load_cli_module()
        for agent in module.AGENTS.values():
            skill = module.render_skill(agent)
            self.assertIn(module.MARKER, skill)
            self.assertIn("second-opinion ask auto", skill)
            self.assertIn("--background", skill)
            self.assertIn("second-opinion wait JOB_ID", skill)
            self.assertIn("model agnostic", skill)
            self.assertIn("Prefer capability fit over model branding", skill)
            self.assertNotIn(f"second-opinion ask {agent.key} --from {agent.key}", skill)
            for key in module.AGENTS:
                self.assertIn(f"`{key}`", skill)

    def test_managed_write_skips_unmanaged_existing_files(self):
        module = load_cli_module()
        with tempfile.TemporaryDirectory() as temp:
            path = Path(temp) / "SKILL.md"
            path.write_text("user content", encoding="utf-8")
            status = module.managed_write(path, "generated", force=False, dry_run=False)
            self.assertEqual("skipped-existing", status)
            self.assertEqual("user content", path.read_text(encoding="utf-8"))


class CliCommandTests(unittest.TestCase):
    def run_cli(self, *args, home=None):
        env = os.environ.copy()
        if home:
            env["SECOND_OPINION_HOME"] = str(home)
        return subprocess.run(
            [str(CLI), *args],
            cwd=str(ROOT),
            env=env,
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            check=False,
        )

    def test_install_all_writes_expected_skill_files(self):
        with tempfile.TemporaryDirectory() as temp:
            home = Path(temp)
            result = self.run_cli("install", "--all", "--yes", home=home)
            self.assertEqual(result.returncode, 0, result.stderr)
            expected = [
                home / ".agents/skills/second-opinion/SKILL.md",
                home / ".claude/skills/second-opinion/SKILL.md",
                home / ".config/opencode/skills/second-opinion/SKILL.md",
                home / ".grok/skills/second-opinion/SKILL.md",
                home / ".gemini/antigravity/skills/second-opinion/SKILL.md",
            ]
            for path in expected:
                self.assertTrue(path.exists(), path)
                self.assertIn("Generated by Second Opinion", path.read_text(encoding="utf-8"))

    def test_status_json_is_valid(self):
        with tempfile.TemporaryDirectory() as temp:
            result = self.run_cli("status", "--json", home=Path(temp))
            self.assertEqual(result.returncode, 0, result.stderr)
            payload = json.loads(result.stdout)
            self.assertEqual(payload["version"], "1.3.1")
            self.assertIn("codex", payload["agents"])
            self.assertIn("antigravity", payload["agents"])

    def test_ask_dry_run_builds_grok_prompt_after_single_flag(self):
        result = self.run_cli("ask", "grok", "--dry-run", "--", "review this")
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertIn("grok", result.stdout)
        self.assertIn("-p", result.stdout)
        self.assertIn("review this", result.stdout)

    def test_codex_dry_run_uses_current_exec_flags(self):
        result = self.run_cli("ask", "codex", "--dry-run", "--", "review this")
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertIn("codex exec", result.stdout)
        self.assertIn("--sandbox read-only", result.stdout)
        self.assertNotIn("--ask-for-approval", result.stdout)

    def test_claude_dry_run_uses_normal_auth_mode(self):
        result = self.run_cli("ask", "claude", "--dry-run", "--", "review this")
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertIn("freedomclaude --idle-ms 8000 --timeout-ms 7200000", result.stdout)
        self.assertIn("-- --permission-mode plan", result.stdout)
        self.assertNotIn("claude -p", result.stdout)
        self.assertNotIn("--print", result.stdout)

    def test_claude_model_override_is_passed_through_freedomclaude(self):
        result = self.run_cli("ask", "claude", "--model", "fable", "--dry-run", "--", "review this")
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertIn("freedomclaude", result.stdout)
        self.assertIn("-- --permission-mode plan --model fable", result.stdout)

    def test_antigravity_dry_run_uses_sandbox_and_print_timeout(self):
        result = self.run_cli("ask", "antigravity", "--dry-run", "--", "review this")
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertIn("agy --print", result.stdout)
        self.assertIn("--sandbox --print-timeout 5m0s", result.stdout)
        self.assertIn("review this", result.stdout)
        self.assertLess(result.stdout.index("--print"), result.stdout.index("review this"))
        self.assertLess(result.stdout.index("review this"), result.stdout.index("--sandbox"))

    def test_antigravity_model_override_is_passed_after_prompt(self):
        result = self.run_cli("ask", "antigravity", "--model", "Gemini 3.5 Flash (Low)", "--dry-run", "--", "review this")
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertIn("--model 'Gemini 3.5 Flash (Low)'", result.stdout)
        self.assertLess(result.stdout.index("review this"), result.stdout.index("--model"))

    def test_antigravity_alias_resolves_for_install(self):
        with tempfile.TemporaryDirectory() as temp:
            home = Path(temp)
            result = self.run_cli("install", "--agent", "agy", "--yes", home=home)
            self.assertEqual(result.returncode, 0, result.stderr)
            path = home / ".gemini/antigravity/skills/second-opinion/SKILL.md"
            self.assertTrue(path.exists(), path)

    def test_timeout_flag_is_deprecated_noop(self):
        module = load_cli_module()
        source = CLI.read_text(encoding="utf-8")
        self.assertIn("Deprecated and ignored", source)
        self.assertNotIn("TimeoutExpired", source)
        self.assertNotIn("subprocess.TimeoutExpired", source)
        self.assertEqual(module.VERSION, "1.3.1")

    def test_update_replaces_cli_from_base_url(self):
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp)
            site_bin = root / "site/bin"
            site_bin.mkdir(parents=True)
            remote_cli = site_bin / "second-opinion"
            remote_cli.write_text(
                "#!/usr/bin/env python3\n"
                '"""Second Opinion CLI."""\n'
                'VERSION = "9.9.9"\n'
                "print('updated second opinion')\n",
                encoding="utf-8",
            )
            target = root / "installed-second-opinion"
            target.write_text(
                "#!/usr/bin/env python3\n"
                '"""Second Opinion CLI."""\n'
                'VERSION = "0.1.0"\n',
                encoding="utf-8",
            )
            target.chmod(0o755)

            result = self.run_cli(
                "update",
                "--base-url",
                (root / "site").as_uri(),
                "--path",
                str(target),
                "--skip-freedomclaude",
                "--skip-skills",
                home=root / "home",
            )
            self.assertEqual(result.returncode, 0, result.stderr)
            self.assertIn("Updated Second Opinion CLI to 9.9.9", result.stdout)
            self.assertIn('VERSION = "9.9.9"', target.read_text(encoding="utf-8"))

    def test_background_job_writes_log_and_metadata(self):
        module = load_cli_module()
        with tempfile.TemporaryDirectory() as temp:
            previous_home = os.environ.get("SECOND_OPINION_HOME")
            os.environ["SECOND_OPINION_HOME"] = temp
            try:
                fake_agent = module.Agent(
                    key="fake",
                    display="Fake Agent",
                    command="fake",
                    skill_path=".fake/SKILL.md",
                    compatibility="fake",
                    aliases=(),
                    strengths="test",
                    consult_args=(),
                    work_args=(),
                )
                rc = module.start_background_job(
                    fake_agent,
                    "consult",
                    [sys.executable, "-c", "print('BACKGROUND_OK')"],
                    Path(temp),
                    "test task",
                )
                self.assertEqual(rc, 0)
                jobs = list((Path(temp) / ".second-opinion/jobs").glob("*.json"))
                self.assertEqual(len(jobs), 1)
                payload = json.loads(jobs[0].read_text(encoding="utf-8"))
                log_path = Path(payload["log_path"])
                for _ in range(50):
                    if log_path.exists() and "BACKGROUND_OK" in log_path.read_text(encoding="utf-8"):
                        break
                    time.sleep(0.1)
                self.assertIn("BACKGROUND_OK", log_path.read_text(encoding="utf-8"))
            finally:
                if previous_home is None:
                    os.environ.pop("SECOND_OPINION_HOME", None)
                else:
                    os.environ["SECOND_OPINION_HOME"] = previous_home


if __name__ == "__main__":
    unittest.main()
